### ISSUE TITLE
label_expression with 🔒 in Property Value variable crashes app

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#387]
In the Drug/Device Documents' _Upload 🔒Investigator Brochure*_ User Task workflow I attempted to add a label_expression Property to the DrugDevDoc_InvestBrochure Form Field with the `InvestBrochure_label` variable.  This variable is set by the following code in the _Load Data_ Script Task and has an embedded 🔒 in the resulting string:
```
InvestBrochure_raw = (ddd.locked_if_uva_irb if isUVA_IRBofRec else ddd.locked_if_non_uva_irb) + ' ' + ddd.description
InvestBrochure_label = InvestBrochure_raw.strip()
```
The task data shows this variable as:
```
"InvestBrochure_label": "🔒 Investigators Brochure"
```

No shield test errors were returned, but when I attempted to run the workflow the app locked up and resetting the study at the Main Dashboard was the only way to proceed.

The presence of a 🔒 in the Form Field Label field does not cause a problem.
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/491ac420-d422-434b-870f-324431edfc5b)

I need to use label_expression since the presence of the 🔒 may change.

**Comment by Leashys** [comment]
@calexh-sar I am 99% sure this was resolved with fixes dan rolled out last week

**Comment by calexh-sar** [comment]
@Leashys I am still seeing an issue with this on testing.  It no longer crashes the app, but when I added
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/8159896c-6732-417d-a062-0b8d39fb78d2)
with task data showing: `InvestBrochure_label": "🔒 Investigators Brochure"`
I get
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/3c77bcab-a43d-4b7e-9b3b-8bd0bd9f3735)

If I remove the `label_expression` and have
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/5323c6ac-0c95-4cef-8d31-2ef40ad950ca)
I get this
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/c41fa73a-50b4-4a5a-a16d-510e501360bd)

**Comment by calexh-sar** [comment]
Working as designed.
