### ISSUE TITLE
Possible False Positive for new Datetime conversion 

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#472]
In the FERPA Approval workflow, I receive this error from the shield test, but the workflow executes without error.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/829b0ed4-f316-4b18-a297-765d67058490)

**Comment by danfunk** [comment]
I did have an issue in validation around date_time parsing, and I think it's fixed in the next release, but with a caveat below.   I also put some effort into assuring we get task_data back all the time, even on script tasks with a function definition in them.


One smaller issue here is that the ferpa_email_sent_utc_str is read in from the data store, and set to None by default:
ferpa_email_sent_utc_str = study_data_get("sdsFERPA_email", None)  (Lin 27 in Load Data)
In the event that it IS null, we get an error on validation "Input type must be a str".  I would recommend putting an if clause around this to check for null, and setting the date string to something like "No Date Provided."

**Comment by calexh-sar** [comment]
@danfunk I am still getting this error.  Did several hard refreshes and seems like other changes have loaded.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/9d1c36ca-a746-48d1-8f77-f4d65e0cf46e)

**Comment by danfunk** [comment]
@calexh-sar  The issue here is validating when using study_data_set, and study_data_get functions.  The validator isn't actually settings these values on the study.  And we'd have to think very hard about how to make this work.  We can't actually effect the study when running the validations, so we can't write to and read from this store.  We would need to have some sort of temp-memory setup for validation.  Which needs to be a different ticket, I will create it. 

There were specific reasons why date validations would fail, and those are fixed.  In the meantime, when validating around a data-store, you will need to assume you can get null back, and handle that case.  Which is not a bad practice generally speaking.  Chaing the code to this will valudate correctly.

```
study_data_set("sdsIDS_email", datetime.datetime.now())
ids_email_sent_utc_str = study_data_get("sdsIDS_email", None)

# Reformat Date Received
if ids_email_sent_utc_str:
  ids_email_sent_utc_dt = dateparser.parse(ids_email_sent_utc_str)
  ids_email_sent_localtime = ids_email_sent_utc_dt.astimezone(pytz.timezone('US/Eastern'))
  ids_email_sent = ids_email_sent_localtime.strftime("%m-%d-%Y")
else:
  ids_email_sent = "No Date Provided"
```

**Comment by calexh-sar** [comment]
Will make those changes, closing for now.
