### ISSUE TITLE
Blank Error when changing Workflow Spec Display Name

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#623]
I edited the Workflow Spec Display Name and upon saving a blank Error popup was presented and [this Sentry error](https://sentry.io/organizations/sartography/issues/3007769691/?referrer=slack) and [this Sentry error](https://sentry.io/organizations/sartography/issues/3019905175/?referrer=slack) were logged.  Upon closing the error popup, I was at the TLW.  When I returned to the Finance Category, the Workflow Spec Display Name had been updated, but the Primary Process was no longer selected.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/1079e752-5eaa-480b-b594-8700fd3b60ef)

Also, it appears all of the Included Libraries were deselected.

Pretty sure that before the recent release editing the Workflow Spec Display Name would not have caused these errors or unselect the Primary Process.

**Comment by cullerton** [comment]
We are not passing libraries, primary_process_id, or primary_file_name to the backend when editing workflow specs.

{
    'id': 'mike_test', 
    'display_name': "Mike's Test", 
    'description': 'Test', 
    'category_id': 'admin_sandbox', 
    'standalone': False, 
    'library': False, 
    'libraries': [], 
    'is_master_spec': False, 
    'primary_file_name': '', 
    'primary_process_id': ''
}

**Comment by cullerton** [comment]
@Leashys I looked at the BPMN code in workflow-spec-dialog.component and couldn't figure out how we call the API. Maybe we can look at this together.

**Comment by Leashys** [comment]
I think this one is working

**Comment by calexh-sar** [comment]
Fixed

**Comment by cullerton** [comment]
This is still not working correctly. We modify the Display Name, but we lose the libraries, primary_file_id, and primary_process_id.

**Comment by cullerton** [comment]
@Leashys Can you show me where you fixed the Display Name part of this, so I can work on the rest of it? I tried looking thru closed BPMN and Sartography Library Pull Requests, to no avail
